package it.unipd.dei.bding.erasmusadvisor.database;

//import it.unipd.dei.bding.erasmusadvisor.beans.StudenteBean;
//
//import java.sql.*;
//
//import org.apache.commons.dbutils.*;
//import org.apache.commons.dbutils.handlers.BeanHandler;

/**
 * Esempio di blocco "finally" corretto per disconnessione db 
 * @author Alessandro
 *
 */

public class DBTest2 {
//		
//
//		private static final String DRIVER = "org.postgresql.Driver";
//		
//		private static final String DATABASE = "jdbc:postgresql://localhost/erasmusadvisor";
//
//		/**
//		 * The username for accessing the database
//		 */
//		private static final String USER = "EATeam";
//
//		/**
//		 * The password for accessing the database
//		 */
//		private static final String PASSWORD = "EATeam";
//		
//		public static void main(String[] args) {
//			
//			Connection con = null;
//			
//			//Statement stmt = null;
//			
//			ResultSet rs = null;
//			
//			try {
//				Class.forName(DRIVER);
//				
//				System.out.printf("Driver %s successfully registered.%n", DRIVER);
//			} catch (ClassNotFoundException e) {
//				System.out.printf("Driver %s not found. %s.%n", DRIVER, e.getMessage());
//				System.exit(-1);
//			}
//			
//		
//		
//		try {
//			con = DriverManager.getConnection(DATABASE, USER, PASSWORD);
//
//			
//			//QueryRunner run = new QueryRunner(dataSource); // GESTIONE AUTOMATICA CONNESSIONI
//			QueryRunner run = new QueryRunner(); // GESTIONE MANUALE CONNESSIONI
//
//			// Use the BeanHandler implementation to convert the first
//			// ResultSet row into a Person JavaBean.
//			ResultSetHandler<StudenteBean> h = new BeanHandler<StudenteBean>(StudenteBean.class);
//
//			// Execute the SQL statement with one replacement parameter and
//			// return the results in a new Person object generated by the BeanHandler.
//			StudenteBean s = run.query(con,
//			    "SELECT * FROM Studente WHERE nomeutente=?", h, "Provaaaaaaaa"); 
//			
//			System.out.println("Trovato: " + s.getEmail() + "" );
//			
//		} catch (SQLException e) {
//			e.printStackTrace();
//		} finally {
//			if (rs != null) {
//				try {
//					rs.close();
//				} catch (SQLException e) {
//				}
//			}
//			/*if (pstmt != null) {
//				try {
//					pstmt.close();
//				} catch (SQLException e) {
//				}
//			}*/
//			if (con != null) {
//				try {
//					con.close();
//				} catch (SQLException e) {
//				}
//			}
//		}
//	}
}